---
subscriber_topic: /scan
publisher_topic: /lidar
robot_availability_topic: /robot_description
wall_follow_min_angle: -120
wall_follow_max_angle: -30

right_wall_min_angle: -90
right_wall_max_angle: -60
front_wall_min_angle: -15
front_wall_max_angle: 15
left_wall_min_angle: 60
left_wall_max_angle: 90

forward_min_angle: -15
forward_max_angle: 0
l_turn_min_angle: 30
l_turn_max_angle: 60
u_turn_min_angle: 105
u_turn_max_angle: 120

intersection_detection_lost_wall_percent_threshold: 0.6
lost_wall_tunnel_width_percent_threshold: 1.5
idle_sleep_duration: 1.0
queue_size: 10