---
beliefs_subscriber_topic: /beliefs
action_status_subscriber_topic: /action_status
actions_publisher_topic: /actions
sleep_duration: 100
queue_size: 10

speed: 0.8 # in meters per second
angle_change_tolerance: 5.0 # in degrees
wall_follow_distance_setpoint: 0.8 # in meters
wall_follow_aim_angle: 30.0 # in degrees
l_turn_aim_angle: 30.0 # in degrees
u_turn_aim_angle: 70.0 # in degrees

# this is the amount of time in seconds where an action is executed by the robot
# this value was obtained by multiplying the Hermes' refresh rate of 0.1s with Create 3's cmd_vel timeout value of 0.5s.
action_execution_duration: 0.05 # in seconds