---
beliefs_subscriber_topic: /beliefs
action_status_subscriber_topic: /action_status
actions_publisher_topic: /actions
sleep_duration: 100
queue_size: 10

speed: 0.4 # in meters per second
angle_change_tolerance: 5.0 # in degrees
wall_follow_distance_setpoint: 0.5 # in meters
wall_follow_aim_angle: 45.0 # in degrees
l_turn_aim_angle: 60.0 # in degrees
u_turn_aim_angle: 115.0 # in degrees

# this is the amount of time in seconds that an action is executed for by the robot
# this value is the same as Hermes' refresh rate (0.1s), since each cmd_vel is only executed up until the next one.
action_execution_duration: 0.1 # in seconds