---
beliefs_subscriber_topic: /beliefs
action_status_subscriber_topic: /action_status
actions_publisher_topic: /actions
sleep_duration: 100
speed: 0.8 # in meters per second
angle_change_tolerance: 5.0 # in degrees
wall_follow_distance_setpoint: 0.8 # in meters
wall_follow_aim_angle: 45.0 # in degrees
l_turn_aim_angle: 45.0 # in degrees
u_turn_aim_angle: 112.0 # in degrees