---
# The name of the file for the generated world
world_name: output.world
wall_height: 3.0
tunnel_width: 5.0
wall_thickness: 0.1
obstacle_height: 0.5
obstacle_radius: 0.25
# The distance between the dock station and its beacon
dock_offset: 0.5
